// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package definition

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Resource to be managed
type Contact struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Id                   int32    `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Contact) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Contact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Contact) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Request sent to Read current DB values
type ReadDBRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadDBRequest) Reset()         { *m = ReadDBRequest{} }
func (m *ReadDBRequest) String() string { return proto.CompactTextString(m) }
func (*ReadDBRequest) ProtoMessage()    {}
func (*ReadDBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *ReadDBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDBRequest.Unmarshal(m, b)
}
func (m *ReadDBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDBRequest.Marshal(b, m, deterministic)
}
func (m *ReadDBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDBRequest.Merge(m, src)
}
func (m *ReadDBRequest) XXX_Size() int {
	return xxx_messageInfo_ReadDBRequest.Size(m)
}
func (m *ReadDBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDBRequest proto.InternalMessageInfo

func (m *ReadDBRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Reply with contacts
type ReadDBReply struct {
	Message              string     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Contacts             []*Contact `protobuf:"bytes,2,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadDBReply) Reset()         { *m = ReadDBReply{} }
func (m *ReadDBReply) String() string { return proto.CompactTextString(m) }
func (*ReadDBReply) ProtoMessage()    {}
func (*ReadDBReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *ReadDBReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDBReply.Unmarshal(m, b)
}
func (m *ReadDBReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDBReply.Marshal(b, m, deterministic)
}
func (m *ReadDBReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDBReply.Merge(m, src)
}
func (m *ReadDBReply) XXX_Size() int {
	return xxx_messageInfo_ReadDBReply.Size(m)
}
func (m *ReadDBReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDBReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDBReply proto.InternalMessageInfo

func (m *ReadDBReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReadDBReply) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func init() {
	proto.RegisterType((*Contact)(nil), "definition.Contact")
	proto.RegisterType((*ReadDBRequest)(nil), "definition.ReadDBRequest")
	proto.RegisterType((*ReadDBReply)(nil), "definition.ReadDBReply")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x49, 0x4a, 0xda, 0xe6, 0x42, 0x3b, 0x1c, 0x48, 0x18, 0x10, 0x52, 0xc8, 0x14, 0x96,
	0x20, 0x95, 0x9d, 0x01, 0x98, 0x2b, 0x94, 0x2e, 0x6c, 0x95, 0x9b, 0x5c, 0x8b, 0xa5, 0xd8, 0x0e,
	0xb6, 0x8b, 0xd4, 0x3f, 0xc1, 0x6f, 0x46, 0x38, 0x84, 0x0f, 0x89, 0x8e, 0xf7, 0x3c, 0xaf, 0xe5,
	0xbb, 0x17, 0x26, 0xd6, 0x69, 0xc3, 0x37, 0x54, 0xb4, 0x46, 0x3b, 0x8d, 0x50, 0xd3, 0x5a, 0x28,
	0xe1, 0x84, 0x56, 0xd9, 0x7b, 0x00, 0xa3, 0x07, 0xad, 0x1c, 0xaf, 0x1c, 0x5e, 0x02, 0xac, 0x85,
	0xb1, 0x6e, 0xa9, 0xb8, 0x24, 0x16, 0xa4, 0x41, 0x1e, 0x97, 0xb1, 0x27, 0x73, 0x2e, 0x09, 0x2f,
	0x20, 0x6e, 0x78, 0x6f, 0x43, 0x6f, 0xc7, 0x9f, 0xc0, 0xcb, 0x2b, 0x38, 0x6a, 0x5f, 0xb4, 0xa2,
	0xa5, 0xda, 0xca, 0x15, 0x19, 0x36, 0xf0, 0x3e, 0xf1, 0x6c, 0xee, 0x11, 0x9e, 0x40, 0x44, 0x92,
	0x8b, 0x86, 0x1d, 0x7a, 0xd7, 0x0d, 0x38, 0x85, 0x50, 0xd4, 0x2c, 0x4a, 0x83, 0x3c, 0x2a, 0x43,
	0x51, 0x67, 0xd7, 0x30, 0x29, 0x89, 0xd7, 0x8f, 0xf7, 0x25, 0xbd, 0x6e, 0xc9, 0x3a, 0x64, 0x30,
	0x92, 0x64, 0x2d, 0xdf, 0xf4, 0x2b, 0xf5, 0x63, 0xf6, 0x0c, 0x49, 0x1f, 0x6d, 0x9b, 0xdd, 0xfe,
	0x20, 0xde, 0xc0, 0xb8, 0xea, 0x6e, 0xb4, 0x2c, 0x4c, 0x07, 0x79, 0x32, 0x3b, 0x2e, 0x7e, 0x3a,
	0x28, 0xbe, 0xee, 0x2f, 0xbf, 0x43, 0xb3, 0x27, 0x98, 0x2e, 0xba, 0xca, 0x16, 0x64, 0xde, 0x44,
	0x45, 0x78, 0x07, 0xc3, 0xee, 0x2f, 0x3c, 0xfb, 0xfd, 0xf4, 0xcf, 0xaa, 0xe7, 0xa7, 0xff, 0xa9,
	0xb6, 0xd9, 0x65, 0x07, 0xab, 0xa1, 0xaf, 0xfe, 0xf6, 0x23, 0x00, 0x00, 0xff, 0xff, 0xae, 0x89,
	0x16, 0x95, 0x8b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	// Manages a set of Contacts
	ReadDB(ctx context.Context, in *ReadDBRequest, opts ...grpc.CallOption) (*ReadDBReply, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) ReadDB(ctx context.Context, in *ReadDBRequest, opts ...grpc.CallOption) (*ReadDBReply, error) {
	out := new(ReadDBReply)
	err := c.cc.Invoke(ctx, "/definition.StorageService/ReadDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	// Manages a set of Contacts
	ReadDB(context.Context, *ReadDBRequest) (*ReadDBReply, error)
}

// UnimplementedStorageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServiceServer struct {
}

func (*UnimplementedStorageServiceServer) ReadDB(ctx context.Context, req *ReadDBRequest) (*ReadDBReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDB not implemented")
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_ReadDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definition.StorageService/ReadDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadDB(ctx, req.(*ReadDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "definition.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadDB",
			Handler:    _StorageService_ReadDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
